# location: $HOME/.zsh/git-helpers.zsh

# =========================
# Internal helpers
# =========================

_gitrel_is_release_branch() {
  local branch="$1"
  local release_branch_pattern='^release/v[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)?$'
  [[ "$branch" =~ $release_branch_pattern ]]
}

_gitrel_commit_exists() {
  local commit_hash="$1"
  git rev-parse --quiet "$commit_hash" 2>/dev/null
}

_gitrel_commit_in_main() {
  local commit_hash="$1"
  if git merge-base --is-ancestor "$commit_hash" main 2>/dev/null; then
    return 0
  fi
  if git merge-base --is-ancestor "$commit_hash" origin/main 2>/dev/null; then
    return 0
  fi
  return 1
}

_gitrel_get_jira_base() {
  shed-kv get jira_url
}

_gitrel_get_remote_info() {
  local remote_url
  remote_url=$(git remote get-url origin 2>/dev/null)

  if [[ "$remote_url" =~ github\.com[:/]([^/]+)/([^/]+)(\.git)?$ ]]; then
    echo "${match[1]}" "${match[2]%.git}"
  fi
}

_gitrel_parse_jira_refs() {
  local message="$1"
  local jira_pattern='\[?([A-Za-z]{2,4}-[0-9]{2,4})\]?'
  local -a jira_ids

  while read -r line; do
    [[ -n "$line" ]] && jira_ids+=("$line")
  done < <(echo "$message" | grep -oE $jira_pattern | sed 's/\[//g; s/\]//g')

  echo "${jira_ids[@]}"
}

_gitrel_parse_pr_refs() {
  local message="$1"
  local pr_pattern='#([0-9]+)'
  local -a pr_nums

  while read -r line; do
    [[ -n "$line" ]] && pr_nums+=("${line#\#}")
  done < <(echo "$message" | grep -oE $pr_pattern)

  echo "${pr_nums[@]}"
}

_gitrel_format_jira_link() {
  local jira_id="$1"
  local jira_base="$2"
  echo "[$jira_id]($jira_base/browse/$jira_id)"
}

_gitrel_format_pr_link() {
  local pr_num="$1"
  local pr_base="$2"
  echo "[#$pr_num]($pr_base/$pr_num)"
}

_gitrel_format_commit_link() {
  local commit_hash="$1"
  local org="$2"
  local repo="$3"

  local short="${commit_hash:0:7}"

  if [[ -n "$org" && -n "$repo" ]]; then
    echo "[\`$short\`](https://github.com/$org/$repo/commit/$commit_hash)"
  else
    echo "\`$short\`"
  fi
}

_gitrel_get_changelog_path() {
  local branch="$1"
  local repo_root
  repo_root=$(git rev-parse --show-toplevel)
  echo "$repo_root/tmp/${branch}.md"
}

_gitrel_ensure_changelog() {
  local changelog_file="$1"
  local branch="$2"

  mkdir -p "$(dirname "$changelog_file")"

  if [[ ! -f "$changelog_file" ]]; then
    echo "# $branch" > "$changelog_file"
    echo "" >> "$changelog_file"
    echo "<!-- Auto-generated by add_to_release -->" >> "$changelog_file"
  fi
}

_gitrel_cherry_pick_commit() {
  local commit_hash="$1"

  local -a pick_output
  pick_output=($(git cherry-pick "$commit_hash" --no-commit 2>&1))

  if [[ $? -ne 0 ]]; then
    echo "Error cherry-picking commit:"
    echo "$pick_output"
    return 1
  fi

  git cherry-pick --quit &>/dev/null
  return 0
}

# =========================
# Release branch helpers
# =========================

addtorelease() {
  local commit_hash="$1"

  if [[ -z "$commit_hash" ]]; then
    echo "Usage: add_to_release <commit_hash>"
    return 1
  fi

  local current_branch
  current_branch=$(git rev-parse --abbrev-ref HEAD)

  if ! _gitrel_is_release_branch "$current_branch"; then
    echo "Error: Not on a release branch. Current branch: $current_branch"
    echo "Release branches must match: release/vX.Y.Z(-rcN)"
    return 1
  fi

  commit_hash=$(_gitrel_commit_exists "$commit_hash")
  if [[ -z "$commit_hash" ]]; then
    echo "Error: Commit $1 does not exist"
    return 1
  fi

  if ! _gitrel_commit_in_main "$commit_hash"; then
    echo "Error: Commit $commit_hash is not in main or origin/main"
    return 1
  fi

  _gitrel_cherry_pick_commit "$commit_hash" || return 1

  local changelog_file
  changelog_file=$(_gitrel_get_changelog_path "$current_branch")

  _gitrel_ensure_changelog "$changelog_file" "$current_branch"

  local full_message subject jira_base org repo
  full_message=$(git log -1 --format="%B" "$commit_hash")
  subject=$(git log -1 --format="%s" "$commit_hash")

  jira_base=$(_gitrel_get_jira_base)
  read -r org repo <<< "$(_gitrel_get_remote_info)"

  local -a jira_links pr_links

  local -a jira_ids
  jira_ids=($(_gitrel_parse_jira_refs "$full_message"))
  for jira_id in $jira_ids; do
    jira_links+=("$(_gitrel_format_jira_link "$jira_id" "$jira_base")")
  done

  local -a pr_nums
  pr_nums=($(_gitrel_parse_pr_refs "$full_message"))

  if [[ ${#pr_nums[@]} -gt 0 && -n "$org" && -n "$repo" ]]; then
    local pr_base="https://github.com/$org/$repo/pull"
    for pr_num in $pr_nums; do
      pr_links+=("$(_gitrel_format_pr_link "$pr_num" "$pr_base")")
    done
  fi

  local commit_link="$(_gitrel_format_commit_link "$commit_hash" "$org" "$repo")"

  local formatted_message="$commit_link $subject"

  local -a parts
  [[ ${#jira_links[@]} -gt 0 ]] && parts+=("${jira_links[*]}")
  [[ ${#pr_links[@]} -gt 0 ]] && parts+=("${pr_links[*]}")

  if [[ ${#parts[@]} -gt 0 ]]; then
    formatted_message+=" (${(j:; :)parts})"
  fi

  echo "- $formatted_message" >> "$changelog_file"

  local short="${commit_hash:0:7}"
  echo "✓ Added $short to $current_branch"
  echo "  → $changelog_file"
}